### ISSUE TITLE
this required my cookies

### ISSUE THREAD

**Issue by Maxey1950** [Scriptifer/Roblox-Immersive-Ad-Blocker#1]
if it requires my cookies its a fucking logger

**Comment by Scriptifer** [comment]
it says the server will see your cookies it doesnt say it needs it, just type no and hit enter

**Comment by Scriptifer** [comment]
what it means by the question is that if you want to connect to a mitm server but the server will see your cookies

**Comment by Scriptifer** [comment]
the question that the console is asking

**Comment by Scriptifer** [comment]
so type no
